version: "3.7"
services:
  mongo-container:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    command: mongod

  mysql:
    image: mysql:5.7.40
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "33066:3306"

  # flask_app:
  #   build: '.'
  #   environment:
  #     - REDIS_URL=redis
  #     - REDIS_PORT=6380
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - '.:/app'
  #   depends_on:
  #     - redis
  #     - mysql
  #     - mongo-container

  simple_worker:
    build: './simple_worker'
    user: nobody
    depends_on:
      - redis
      # - flask_app

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6380:6379'